### ISSUE TITLE
jdbc connector drivers

### ISSUE THREAD

**Issue by AmeliaMcV** [gertschouten/kafka-connect-jdbc-flatten#6]
Hi we are looking to use this extension to sink data into mysql db. 
We have found that we need the mysql jdbc drivers installed to be able to do this. 
With the original version of this connector we successfully installed these in:
 
`/usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib  `

Could I ask if the mysql jdbc driver is needed for this extended version of the jdbc connector and if so what is the directory path for where the driver would need to be installed?

Many thanks, 

Amelia

**Comment by gertschouten** [comment]
Hi Amelia.
Can you put your driver in the connector directory that gets packaged to /target/components/packages/<connector directory>..when you do maven package.

And then have this container directory on the plugin.path of the connect cluster. This so that the connect classloader picks up the connector class, libraries and drivers it needs when it is class loading the container directory.

Let me know if it helped.

**Comment by AmeliaMcV** [comment]
Hi, 

Thanks for coming back so quickly. 
We are hosting the connector config in a container so we need load the drivers onto the container. 
My colleague has found the docker container directory the drivers need to go into, it's: /usr/share/confluent-hub-components/norsktipping-kafka-connect-jdbc_flatten/lib 

Thanks again, 

Amelia

**Comment by gertschouten** [comment]
Good..Ok... Amelia..
Then let me know if anything else pops up yeah.
Hava a nice weekend.
